import "server-only";
import { createAdminSupabaseClient, createServerSupabaseClient } from "@/lib/supabase/server";
import type { AmcEmailBatch, PublicReport } from "@/lib/supabase/types";
import { addReportEvent } from "@/lib/data/reports";

const PUBLIC_REPORT_COLUMNS = [
  "id",
  "tracking_id",
  "issue_type",
  "title",
  "description",
  "latitude",
  "longitude",
  "address_text",
  "area",
  "district",
  "city",
  "state",
  "country",
  "image_url",
  "image_path",
  "status",
  "severity",
  "verification_level",
  "confirmation_count",
  "created_at",
  "updated_at",
  "approved_at",
  "resolved_at",
  "resolved_claimed_at",
  "citizen_verified_at",
  "reopened_at",
  "sent_to_amc_at",
].join(",");

function adminClient() {
  return createAdminSupabaseClient();
}

function publicClient() {
  return createServerSupabaseClient();
}

function throwSupabaseError(message: string, error: unknown): never {
  const detail =
    error && typeof error === "object" && "message" in error
      ? String((error as { message: unknown }).message)
      : "Unknown Supabase error";
  throw new Error(`${message}: ${detail}`);
}

export async function getAmcBatches(): Promise<AmcEmailBatch[]> {
  const { data, error } = await adminClient()
    .from("amc_email_batches")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) throwSupabaseError("Could not load AMC batches", error);
  return (data || []) as AmcEmailBatch[];
}

export async function getAmcBatchById(id: string): Promise<AmcEmailBatch | null> {
  const { data, error } = await adminClient()
    .from("amc_email_batches")
    .select("*")
    .eq("id", id)
    .maybeSingle();

  if (error) throwSupabaseError("Could not load AMC batch", error);
  return data as AmcEmailBatch | null;
}

export async function createAmcBatch(weekStart: string, weekEnd: string): Promise<AmcEmailBatch> {
  const { data, error } = await adminClient()
    .from("amc_email_batches")
    .insert({
      week_start: weekStart,
      week_end: weekEnd,
      report_count: 0,
      status: "draft",
    })
    .select("*")
    .single();

  if (error) throwSupabaseError("Could not create AMC batch", error);
  return data as AmcEmailBatch;
}

export async function addReportsToBatch(batchId: string, reportIds: string[]): Promise<void> {
  if (reportIds.length === 0) return;

  const rows = reportIds.map((report_id) => ({ batch_id: batchId, report_id }));
  const { error: insertError } = await adminClient()
    .from("amc_email_batch_reports")
    .insert(rows);

  if (insertError) throwSupabaseError("Could not add listings to batch", insertError);

  const { count, error: countError } = await adminClient()
    .from("amc_email_batch_reports")
    .select("id", { count: "exact", head: true })
    .eq("batch_id", batchId);

  if (countError) throwSupabaseError("Could not count batch listings", countError);

  const { error: updateError } = await adminClient()
    .from("amc_email_batches")
    .update({ report_count: count || 0 })
    .eq("id", batchId);

  if (updateError) throwSupabaseError("Could not update batch listing count", updateError);
}

export async function generateBatchEmailBody(batchId: string): Promise<string> {
  const batch = await getAmcBatchById(batchId);
  if (!batch) throw new Error("Export batch not found");

  const reports = await getBatchReports(batchId);

  const lines: string[] = [
    `Lari Local Vendor Batch`,
    `Week: ${batch.week_start} to ${batch.week_end}`,
    `Total Listings: ${reports.length}`,
    ``,
    `---`,
    ``,
  ];

  for (let i = 0; i < reports.length; i++) {
    const r = reports[i];
    lines.push(`Listing #${i + 1}`);
    if (r.tracking_id) lines.push(`Tracking ID: ${r.tracking_id}`);
    lines.push(`Cuisine: ${r.issue_type}`);
    if (r.title) lines.push(`Title: ${r.title}`);
    if (r.menu_text || r.description) lines.push(`Menu: ${r.menu_text || r.description}`);
    lines.push(`Status: ${r.status}`);
    if (r.severity) lines.push(`Review Priority: ${r.severity}`);
    const location = [r.address_text, r.area, r.district, r.city]
      .filter(Boolean)
      .join(", ");
    if (location) lines.push(`Location: ${location}`);
    lines.push(`Coordinates: ${r.latitude}, ${r.longitude}`);
    lines.push(`Submitted On: ${r.created_at}`);
    if (r.image_url) lines.push(`Photo: ${r.image_url}`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`This is an automated vendor export generated by Lari Local.`);

  return lines.join("\n");
}

export async function markBatchSent(
  batchId: string,
  sentTo: string,
  cc?: string,
  subject?: string,
): Promise<AmcEmailBatch> {
  const batch = await getAmcBatchById(batchId);
  if (!batch) throw new Error("Export batch not found");

  const body = await generateBatchEmailBody(batchId);
  const now = new Date().toISOString();

  const { data, error } = await adminClient()
    .from("amc_email_batches")
    .update({
      status: "sent",
      sent_at: now,
      sent_to: sentTo,
      cc: cc || null,
      subject: subject || `Lari Local Vendors — Week ${batch.week_start} to ${batch.week_end}`,
      body,
    })
    .eq("id", batchId)
    .select("*")
    .single();

  if (error) throwSupabaseError("Could not mark batch as sent", error);

  const { data: batchReports, error: reportsError } = await adminClient()
    .from("amc_email_batch_reports")
    .select("report_id")
    .eq("batch_id", batchId);

  if (reportsError) throwSupabaseError("Could not fetch batch listing IDs", reportsError);

  const ELIGIBLE_STATUSES = ["verified", "approved", "in_progress"];
  for (const row of batchReports || []) {
    const reportId = row.report_id as string;

    const { data: report, error: reportError } = await adminClient()
      .from("reports")
      .select("id, status")
      .eq("id", reportId)
      .maybeSingle();

    if (reportError || !report) continue;

    if (ELIGIBLE_STATUSES.includes(report.status)) {
      await adminClient()
        .from("reports")
        .update({ status: "sent_to_amc", sent_to_amc_at: now })
        .eq("id", reportId);

      await addReportEvent(reportId, {
        event_type: "sent_to_amc",
        old_status: report.status,
        new_status: "sent_to_amc",
        note: `Included in vendor export batch ${batchId}.`,
        actor: "admin",
      });
    }
  }

  return data as AmcEmailBatch;
}

export async function getPublicAmcBatches(): Promise<AmcEmailBatch[]> {
  const { data, error } = await publicClient()
    .from("amc_email_batches")
    .select("*")
    .eq("status", "sent")
    .order("sent_at", { ascending: false });

  if (error) throwSupabaseError("Could not load public AMC batches", error);
  return (data || []) as AmcEmailBatch[];
}

export async function getBatchReports(batchId: string): Promise<PublicReport[]> {
  const { data: batchReports, error: batchError } = await publicClient()
    .from("amc_email_batch_reports")
    .select("report_id")
    .eq("batch_id", batchId);

  if (batchError) throwSupabaseError("Could not load batch listing IDs", batchError);
  if (!batchReports || batchReports.length === 0) return [];

  const reportIds = batchReports.map((r) => r.report_id as string);

  const { data, error } = await publicClient()
    .from("reports")
    .select(PUBLIC_REPORT_COLUMNS)
    .in("id", reportIds)
    .order("created_at", { ascending: false });

  if (error) throwSupabaseError("Could not load batch listings", error);
  return (data || []) as unknown as PublicReport[];
}
